@startuml ChangeTeamCompositionProblems
title "Change team compistion problems"

participant "client 1" as c1
participant "Server" as s

== Join the server ==

note over c1
The socket is instanciated and the connection is
automatically established.
end note

c1->s : Establish connection
c1<-->s : Connection established

c1->s: LOGIN Red
s->c1: OK

== POKEDEX ==

c1->s: POKEDEX
s->c1: POKEMON (1. bulbizzare, 2.herbizzare, 3.florizzare,...)
c1->s: POKEDEX bulbizzare
s->c1: STATS Bulbizzare (PV: 45, ATT:49,...)

c1->s: POKEDEX ADD dracaufeu (PV:78, ATT:84,...)
s->c1: OK

== CHANGE team composition==
note over c1
Just as in the real game each trainer only
has 6 pokemon max
end note

c1->s: CHANGE
s->c1: YOUR team (1. bulbizzare, 2.carapuce)
c1->s: CHANGE 1 herbizzare
s->c1: NEW team (1. herbizzare, 2.carapuce)

== CHANGE team with a non existing pokemon ==

c1->s: CHANGE
s->c1: YOUR team (1. herbizzare, 2.carapuce)
c1->s: CHANGE 2 arsene
s->c1: ERROR

== CHANGE team with wrong number of order ==
c1->s: CHANGE
s->c1: YOUR team (1. herbizzare, 2.carapuce)
c1->s: CHANGE 7 carapuce
s->c1: ERROR

@enduml