@startuml JoinPossibleCombatsProblem

title "Join possible combats problem"

participant "client 1" as c1
participant "Server" as s
participant "client 2" as giovanni
participant "client 3" as sacha

== Join the server ==

note over c1,giovanni
The socket is instanciated and the connection is
automatically established.
end note

c1->s : Establish connection
c1<-->s : Connection established

c1->s: LOGIN Red
s->c1: OK

giovanni->s: Establish connection
giovanni<-->: Connection established

giovanni->s: LOGIN Giovanni
s->giovanni: OK

== List possible combats ==

c1->s: JOIN
s->c1: HOSTS giovanni

== JOIN possible combats ==

c1->s: JOIN Giovanni
s->c1: OK

c1->giovanni: Establish connection
c1<-->giovanni: Connection established

== JOIN a combats that isn't here ==

c1->s: JOIN sacha
s->c1: ERROR

== HOST possible combats ==

giovanni->s: HOST
s->giovanni: OK
s->giovanni: RECEIVE matchmaking from Red
s->s: Remove Giovanni from Hosts

giovanni->c1: Establish connection
c1<-->giovanni: Connection established

== JOIN a combats when being an HOST ==
c1->s: HOST
s->c1: OK

c1->s: JOIN giovanni
s->c1: OK
s->s: remove c1 from hosts

c1->giovanni: Establish connection
c1<-->giovanni: Connection established

@enduml