@startuml PokedexProblems
title "Pokedex problems"

participant "client 1" as c1
participant "Server" as s

== Join the server ==

note over c1,giovanni
The socket is instanciated and the connection is
automatically established.
end note

c1->s : Establish connection
c1<-->s : Connection established

c1->s: LOGIN Red
s->c1: OK

== POKEDEX ==

c1->s: POKEDEX
s->c1: POKEMON (bulbizzare, herbizzare, florizzare,...)
c1->s: POKEDEX bulbizzare
s->c1: STATS Bulbizzare Grass/Poison (PV: 45, ATT:49,...)

c1->s: POKEDEX ADD
s->c1: "what is his name"
c1->s: dracaufeu...
s->c1: etc...(question sur le pokémon)
s->c1: OK

== Pokedex don't have this pokemon ==

c1->s: POKEDEX
s->c1: POKEMON (bulbizzare, herbizzare, florizzare,...)
c1->s: POKEDEX arsene
s->c1: ERROR 1




@enduml