@startuml PokedexProblems
title "Pokedex problems"

participant "client 1" as c1
participant "Server" as s

== Join the server ==

note over c1,giovanni
The socket is instanciated and the connection is
automatically established.
end note

c1->s : Establish connection
c1<-->s : Connection established

c1->s: LOGIN Red
s->c1: OK

== POKEDEX ==

c1->s: POKEDEX
s->c1: POKEMON (1. bulbizzare, 2.herbizzare, 3.florizzare,...)
c1->s: POKEDEX bulbizzare
s->c1: STATS Bulbizzare (PV: 45, ATT:49,...)

c1->s: POKEDEX ADD dracaufeu (PV:78, ATT:84,...)
s->c1: OK

== Pokedex don't have this pokemon ==

c1->s: POKEDEX
s->c1: POKEMON (1. bulbizzare, 2.herbizzare, 3.florizzare,...)
c1->s: POKEDEX arsene
s->c1: ERROR

== POKEDEX ADD missing param ==
c1->s: POKEDEX
s->c1: POKEMON (1. bulbizzare, 2.herbizzare, 3.florizzare,...)
c1->s: POKEDEX ADD salamèche (PV:78, DEF:78,...)
s->c1: ERROR


@enduml