@startuml ChangeTeamCompositionProblems
title "Change team compistion problems"

participant "client 1" as c1
participant "Server" as s

== Join the server ==

note over c1
The socket is instanciated and the connection is
automatically established.
end note

c1->s : Establish connection
c1<-->s : Connection established

c1->s: LOGIN Red
s->c1: OK

== CHANGE team composition==
note over c1
Just as in the real game each trainer only
has 6 pokemon max
end note

c1->s: CHANGE
s->c1: YOUR team ( bulbizzare, carapuce)
c1->s: CHANGE 1 herbizzare
s->c1: OK

== CHANGE team with a non existing pokemon ==

c1->s: CHANGE
s->c1: YOUR team (1. herbizzare, 2.carapuce)
c1->s: CHANGE 2 arsene
s->c1: ERROR 1

== CHANGE team with wrong number of order ==
c1->s: CHANGE
s->c1: YOUR team (1. herbizzare, 2.carapuce)
c1->s: CHANGE 7 carapuce
s->c1: ERROR 2

== CHANGE lacks a parameter ==
c1->s: CHANGE
s->c1: YOUR team (1. herbizzare, 2.carapuce)
c1->s: CHANGE 4
s->c1: ERROR 3

@enduml